alertmanager:
  enabled: false
prometheus:
  enabled: true
rbac:
  create: true
  pspEnabled: false
coreDns:
  enabled: false
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false
kubeScheduler:
  enabled: false
kube-state-metrics:
  rbac:
    create: true
    pspEnabled: false
node-exporter:
  rbac:
    create: true
    pspEnabled: false
extraDeploy:
  # Service Monitor rules
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: cilium-agent
      namespace: monitoring
      labels:
        app.kubernetes.io/instance: cilium
        app.kubernetes.io/name: cilium
        app.kubernetes.io/part-of: cilium
        app.kubernetes.io/component: agent
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/instance: cilium
          app.kubernetes.io/name: cilium
          app.kubernetes.io/part-of: cilium
          app.kubernetes.io/component: agent
          prometheus.io/scrape: "true"
      endpoints:
        - port: tcp-metrics
          path: /metrics
      namespaceSelector:
        matchNames:
          - kube-system
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: cilium-envoy
      namespace: monitoring
      labels:
        app.kubernetes.io/instance: cilium
        app.kubernetes.io/name: cilium
        app.kubernetes.io/part-of: cilium
        app.kubernetes.io/component: envoy
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/instance: cilium
          app.kubernetes.io/name: cilium
          app.kubernetes.io/part-of: cilium
          app.kubernetes.io/component: envoy
          prometheus.io/scrape: "true"
      endpoints:
        - port: tcp-metrics
          path: /metrics
      namespaceSelector:
        matchNames:
          - kube-system
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: cilium-hubble-relay
      namespace: monitoring
      labels:
        app.kubernetes.io/instance: cilium
        app.kubernetes.io/name: cilium
        app.kubernetes.io/part-of: cilium
        app.kubernetes.io/component: hubble-relay
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/instance: cilium
          app.kubernetes.io/name: cilium
          app.kubernetes.io/part-of: cilium
          app.kubernetes.io/component: hubble-relay
      endpoints:
        - port: tcp-metrics
          path: /metrics
      namespaceSelector:
        matchNames:
          - kube-system
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: cilium-operator
      namespace: monitoring
      labels:
        app.kubernetes.io/instance: cilium
        app.kubernetes.io/name: cilium
        app.kubernetes.io/part-of: cilium
        app.kubernetes.io/component: operator
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/instance: cilium
          app.kubernetes.io/name: cilium
          app.kubernetes.io/part-of: cilium
          app.kubernetes.io/component: operator
          prometheus.io/scrape: "true"
      endpoints:
        - port: tcp-metrics
          path: /metrics
      namespaceSelector:
        matchNames:
          - kube-system
