apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-cd
spec:
  project: cd
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: cert-manager
      targetRevision: 1.3.20
      helm:
        valueFiles:
          - $values/infrastructure/charts-values/kube-system/cert-manager.yaml
    - repoURL: https://github.com/juan131/cilium-demo.git
      targetRevision: deployed
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      # Delete resources when Argo CD detects the resource is no longer defined in Git
      prune: true
    syncOptions:
      # Ensures that namespace specified as the application destination exists in the destination cluster
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
